name: Build and Test

permissions:
  actions: read
  contents: read

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake `
            -B build `
            -G Ninja `
            --toolchain=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: ctest --test-dir build

  build_macos:
    name: Build and Test on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
          MACOSX_DEPLOYMENT_TARGET: 15.0
          ARCHFLAGS: "-arch arm64"
        run: |
          cmake \
            -B build \
            -G Ninja \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: ctest --test-dir build

  build_linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake \
            -B build \
            -G Ninja \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: ctest --test-dir build
